# -*- coding: utf-8 -*-
"""HarrisFootball_QBRankings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17IeUTUhLqoTm0FdM4I2t_d-0O324gPFO
"""

from requests import get
from requests.exceptions import RequestException
from contextlib import closing
from bs4 import BeautifulSoup
import csv
from utilities.utility_data import insert_data, convert_to_integer, get_team_by_name, get_player_by_name
from utilities.utility_scrape import simple_get
from utilities.utility_players import find_player_id_by_name

def is_good_response(resp):
    """
    Returns True if the response seems to be HTML, False otherwise.
    """
    content_type = resp.headers['Content-Type'].lower()
    return (resp.status_code == 200
            and content_type is not None
            and content_type.find('html') > -1)


def log_error(e):
    """
    It is always a good idea to log errors.
    This function just prints them, but you can
    make it do anything.
    """
    print(e)

# QB RANKS
raw_html = simple_get('https://www.harrisfootball.com/ranks-draft')
html = BeautifulSoup(raw_html, 'html.parser')

# when ranks last updated
blockContent = html.find('div', {'class': 'sqs-block-content'})
p = blockContent.findAll('p')[1].text
print(p)

tr = html.findAll('tr')
trLength = len(tr)
print(trLength)

playerData = []

for row in range(0,trLength):

    td_list = tr[row].findAll('td')

    player = {}

    playerHarrisQBRank = td_list[0].text
    playerName = td_list[1].text

    player['HarrisQBRank'] = playerHarrisQBRank
    player['Name'] = playerName
    print(player)
    playerData.append(player)

# print(playerData)

with open('csv/HarrisQBRank.csv', 'w') as csvfile:
    filewriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)

    for player in playerData:
        rank = player['HarrisQBRank']
        print(rank)
        name = player['Name']
        print(name)
        name = get_player_by_name(name)
        # print(name)
        # player_id = name[0]

        filewriter.writerow(['HarrisQBRank', name[0], rank])

